steps:
  # Build the Docker image for the Go application
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/trec-incubation-hackathon/backend', '.']

  # Push the Docker image for the Go application to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/trec-incubation-hackathon/backend']


options:
  logging: CLOUD_LOGGING_ONLY
