version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdbname
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: youruser
      DB_PASSWORD: yourpassword
      DB_NAME: yourdbname
      DB_PORT: 5432
      JWT_SECRET: your_secret_key
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: ["./main"]

volumes:
  db_data:
